import enum,uuid
from datetime import datetime,timezone
from sqlalchemy import Boolean,DateTime,Enum,ForeignKey,Integer,BigInteger,String,Text,UniqueConstraint,CheckConstraint,Index
from sqlalchemy.orm import Mapped,mapped_column
from .db import Base
def now():return datetime.now(timezone.utc)
def uid():return str(uuid.uuid4())
class RoleName(str,enum.Enum): platform_owner="platform_owner";tenant_manager="tenant_manager";tenant_operator="tenant_operator";client="client"
class NodeState(str,enum.Enum): discovered="DISCOVERED";authenticating="AUTHENTICATING";installing="INSTALLING";configuring="CONFIGURING";health_check="HEALTH_CHECK";syncing="SYNCING";ready="READY";degraded="DEGRADED";offline="OFFLINE";provision_failed="PROVISION_FAILED";quarantined="QUARANTINED"
class Protocol(str,enum.Enum): wireguard="wireguard";amneziawg="amneziawg";openvpn="openvpn"
class ResourceState(str,enum.Enum): active="ACTIVE";suspended="SUSPENDED";expired="EXPIRED";revoked="REVOKED"
class Tenant(Base):
 __tablename__="tenants"
 id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);name:Mapped[str]=mapped_column(String(160));slug:Mapped[str]=mapped_column(String(100),unique=True);enabled:Mapped[bool]=mapped_column(Boolean,default=True);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class Admin(Base):
 __tablename__="admins"
 id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);tenant_id:Mapped[str|None]=mapped_column(ForeignKey("tenants.id",ondelete="CASCADE"),index=True);email:Mapped[str]=mapped_column(String(320),unique=True);password_hash:Mapped[str]=mapped_column(String(512));role:Mapped[RoleName]=mapped_column(Enum(RoleName),default=RoleName.tenant_operator);enabled:Mapped[bool]=mapped_column(Boolean,default=True);mfa_secret_encrypted:Mapped[str|None]=mapped_column(Text);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class Role(Base):
 __tablename__="roles"
 id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);tenant_id:Mapped[str|None]=mapped_column(ForeignKey("tenants.id",ondelete="CASCADE"),index=True);name:Mapped[str]=mapped_column(String(100));description:Mapped[str|None]=mapped_column(Text);__table_args__=(UniqueConstraint("tenant_id","name"),)
class Permission(Base):
 __tablename__="permissions"
 id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);key:Mapped[str]=mapped_column(String(160),unique=True)
class AdminRole(Base):
 __tablename__="admin_roles";admin_id:Mapped[str]=mapped_column(ForeignKey("admins.id",ondelete="CASCADE"),primary_key=True);role_id:Mapped[str]=mapped_column(ForeignKey("roles.id",ondelete="CASCADE"),primary_key=True)
class AdminPermission(Base):
 __tablename__="admin_permissions";admin_id:Mapped[str]=mapped_column(ForeignKey("admins.id",ondelete="CASCADE"),primary_key=True);permission_id:Mapped[str]=mapped_column(ForeignKey("permissions.id",ondelete="CASCADE"),primary_key=True)
class Node(Base):
 __tablename__="nodes"
 id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.id",ondelete="CASCADE"),index=True);name:Mapped[str]=mapped_column(String(160));address:Mapped[str]=mapped_column(String(255));agent_url:Mapped[str|None]=mapped_column(String(512));state:Mapped[NodeState]=mapped_column(Enum(NodeState),default=NodeState.discovered);agent_version:Mapped[str|None]=mapped_column(String(40));capabilities:Mapped[str]=mapped_column(Text,default="{}");last_seen_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class NodeCredential(Base):
 __tablename__="node_credentials"
 id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);node_id:Mapped[str]=mapped_column(ForeignKey("nodes.id",ondelete="CASCADE"),index=True);fingerprint:Mapped[str]=mapped_column(String(255),unique=True);credential_hash:Mapped[str]=mapped_column(String(512));expires_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));revoked_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class Inbound(Base):
 __tablename__="inbounds"
 id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.id",ondelete="CASCADE"),index=True);node_id:Mapped[str]=mapped_column(ForeignKey("nodes.id",ondelete="CASCADE"),index=True);name:Mapped[str]=mapped_column(String(160));protocol:Mapped[Protocol]=mapped_column(Enum(Protocol));listen_port:Mapped[int]=mapped_column(Integer);interface:Mapped[str]=mapped_column(String(80));address:Mapped[str]=mapped_column(String(120));network:Mapped[str]=mapped_column(String(120));dns:Mapped[str|None]=mapped_column(String(255));mtu:Mapped[int|None]=mapped_column(Integer);enabled:Mapped[bool]=mapped_column(Boolean,default=True);desired_state:Mapped[str]=mapped_column(String(30),default="ACTIVE");created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now);__table_args__=(UniqueConstraint("node_id","listen_port"),CheckConstraint("listen_port>0 AND listen_port<65536"),)
class InboundWireGuard(Base):
 __tablename__="inbound_wireguard";inbound_id:Mapped[str]=mapped_column(ForeignKey("inbounds.id",ondelete="CASCADE"),primary_key=True);server_public_key:Mapped[str]=mapped_column(String(64));server_private_key_encrypted:Mapped[str|None]=mapped_column(Text);amnezia_junk:Mapped[int|None]=mapped_column(Integer);amnezia_init:Mapped[int|None]=mapped_column(Integer);amnezia_response:Mapped[int|None]=mapped_column(Integer);amnezia_cookie:Mapped[int|None]=mapped_column(Integer);amnezia_s1:Mapped[int]=mapped_column(Integer,default=80);amnezia_s2:Mapped[int]=mapped_column(Integer,default=120);amnezia_s3:Mapped[int]=mapped_column(Integer,default=0);amnezia_s4:Mapped[int]=mapped_column(Integer,default=0);amnezia_h1:Mapped[int]=mapped_column(BigInteger,default=123456789);amnezia_h2:Mapped[int]=mapped_column(BigInteger,default=223456789);amnezia_h3:Mapped[int]=mapped_column(BigInteger,default=323456789);amnezia_h4:Mapped[int]=mapped_column(BigInteger,default=423456789)
class InboundOpenVPN(Base):
 __tablename__="inbound_openvpn";inbound_id:Mapped[str]=mapped_column(ForeignKey("inbounds.id",ondelete="CASCADE"),primary_key=True);transport:Mapped[str]=mapped_column(String(8),default="udp");server_network:Mapped[str]=mapped_column(String(120));tls_min:Mapped[str]=mapped_column(String(20),default="1.2");tls_crypt:Mapped[bool]=mapped_column(Boolean,default=True);cipher_policy:Mapped[str]=mapped_column(String(255),default="AES-256-GCM:AES-128-GCM");ca_pem:Mapped[str|None]=mapped_column(Text);server_cert_pem:Mapped[str|None]=mapped_column(Text);server_key_encrypted:Mapped[str|None]=mapped_column(Text);ca_key_encrypted:Mapped[str|None]=mapped_column(Text);crl_pem:Mapped[str|None]=mapped_column(Text);tls_crypt_key_encrypted:Mapped[str|None]=mapped_column(Text)
class Client(Base):
 __tablename__="clients";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.id",ondelete="CASCADE"),index=True);inbound_id:Mapped[str]=mapped_column(ForeignKey("inbounds.id",ondelete="CASCADE"),index=True);name:Mapped[str]=mapped_column(String(160));status:Mapped[ResourceState]=mapped_column(Enum(ResourceState),default=ResourceState.active);assigned_address:Mapped[str]=mapped_column(String(120));expires_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now);__table_args__=(UniqueConstraint("tenant_id","inbound_id","name"),UniqueConstraint("tenant_id","inbound_id","assigned_address"))
class ClientCredential(Base):
 __tablename__="client_credentials";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);client_id:Mapped[str]=mapped_column(ForeignKey("clients.id",ondelete="CASCADE"),index=True);device_id:Mapped[str|None]=mapped_column(ForeignKey("devices.id",ondelete="SET NULL"),index=True);public_identifier:Mapped[str]=mapped_column(String(255));encrypted_private_material:Mapped[str|None]=mapped_column(Text);fingerprint:Mapped[str]=mapped_column(String(255),unique=True);expires_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));revoked_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class Device(Base):
 __tablename__="devices";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.id",ondelete="CASCADE"),index=True);client_id:Mapped[str]=mapped_column(ForeignKey("clients.id",ondelete="CASCADE"),index=True);fingerprint:Mapped[str]=mapped_column(String(255));assigned_address:Mapped[str|None]=mapped_column(String(120));last_seen_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))
class Session(Base):
 __tablename__="sessions";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.id",ondelete="CASCADE"),index=True);client_id:Mapped[str]=mapped_column(ForeignKey("clients.id",ondelete="CASCADE"),index=True);node_id:Mapped[str]=mapped_column(ForeignKey("nodes.id",ondelete="CASCADE"),index=True);inbound_id:Mapped[str]=mapped_column(ForeignKey("inbounds.id",ondelete="CASCADE"),index=True);endpoint:Mapped[str|None]=mapped_column(String(255));bytes_in:Mapped[int]=mapped_column(BigInteger,default=0);bytes_out:Mapped[int]=mapped_column(BigInteger,default=0);started_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now);last_seen_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now);ended_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))
class TrafficUsage(Base):
 __tablename__="traffic_usage";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.id",ondelete="CASCADE"),index=True);client_id:Mapped[str]=mapped_column(ForeignKey("clients.id",ondelete="CASCADE"),index=True);node_id:Mapped[str]=mapped_column(ForeignKey("nodes.id",ondelete="CASCADE"),index=True);inbound_id:Mapped[str]=mapped_column(ForeignKey("inbounds.id",ondelete="CASCADE"),index=True);bytes_in:Mapped[int]=mapped_column(BigInteger,default=0);bytes_out:Mapped[int]=mapped_column(BigInteger,default=0);first_seen:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now);last_seen:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class TrafficSnapshot(Base):
 __tablename__="traffic_snapshots"
 id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid)
 tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.id",ondelete="CASCADE"),index=True)
 client_id:Mapped[str]=mapped_column(ForeignKey("clients.id",ondelete="CASCADE"),index=True)
 node_id:Mapped[str]=mapped_column(ForeignKey("nodes.id",ondelete="CASCADE"),index=True)
 inbound_id:Mapped[str]=mapped_column(ForeignKey("inbounds.id",ondelete="CASCADE"),index=True)
 bytes_in:Mapped[int]=mapped_column(BigInteger,default=0)
 bytes_out:Mapped[int]=mapped_column(BigInteger,default=0)
 captured_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,index=True)

class Quota(Base):
 __tablename__="quotas";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.id",ondelete="CASCADE"),index=True);client_id:Mapped[str]=mapped_column(ForeignKey("clients.id",ondelete="CASCADE"),unique=True);total_bytes:Mapped[int|None]=mapped_column(BigInteger);daily_bytes:Mapped[int|None]=mapped_column(BigInteger);monthly_bytes:Mapped[int|None]=mapped_column(BigInteger);max_devices:Mapped[int|None]=mapped_column(Integer);warning_ratio:Mapped[int]=mapped_column(Integer,default=80);state:Mapped[str]=mapped_column(String(30),default="NORMAL");expires_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))
class ConfigArtifact(Base):
 __tablename__="config_artifacts";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.id",ondelete="CASCADE"),index=True);client_id:Mapped[str]=mapped_column(ForeignKey("clients.id",ondelete="CASCADE"),index=True);protocol:Mapped[Protocol]=mapped_column(Enum(Protocol));fingerprint:Mapped[str]=mapped_column(String(255),unique=True);encrypted_payload:Mapped[str]=mapped_column(Text);expires_at:Mapped[datetime]=mapped_column(DateTime(timezone=True));downloaded_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))
class ProvisioningTask(Base):
 __tablename__="provisioning_tasks";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.id",ondelete="CASCADE"),index=True);node_id:Mapped[str]=mapped_column(ForeignKey("nodes.id",ondelete="CASCADE"),index=True);idempotency_key:Mapped[str]=mapped_column(String(255),unique=True);state:Mapped[str]=mapped_column(String(40),default="DISCOVERED");error:Mapped[str|None]=mapped_column(Text);bootstrap_token_hash:Mapped[str|None]=mapped_column(String(128));bootstrap_expires_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True));created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now);updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,onupdate=now)
class Product(Base):
 __tablename__="products";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);tenant_id:Mapped[str|None]=mapped_column(ForeignKey("tenants.id",ondelete="CASCADE"),index=True);name:Mapped[str]=mapped_column(String(160));description:Mapped[str|None]=mapped_column(Text);enabled:Mapped[bool]=mapped_column(Boolean,default=True);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class Plan(Base):
 __tablename__="plans";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);product_id:Mapped[str]=mapped_column(ForeignKey("products.id",ondelete="CASCADE"),index=True);name:Mapped[str]=mapped_column(String(160));price_minor:Mapped[int]=mapped_column(BigInteger);currency:Mapped[str]=mapped_column(String(3),default="USD");duration_days:Mapped[int]=mapped_column(Integer);traffic_bytes:Mapped[int|None]=mapped_column(BigInteger);enabled:Mapped[bool]=mapped_column(Boolean,default=True)
class Order(Base):
 __tablename__="orders";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.id",ondelete="CASCADE"),index=True);admin_id:Mapped[str|None]=mapped_column(ForeignKey("admins.id",ondelete="SET NULL"));plan_id:Mapped[str]=mapped_column(ForeignKey("plans.id"));idempotency_key:Mapped[str]=mapped_column(String(255),unique=True);status:Mapped[str]=mapped_column(String(30),default="PENDING");total_minor:Mapped[int]=mapped_column(BigInteger);currency:Mapped[str]=mapped_column(String(3));created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class Payment(Base):
 __tablename__="payments";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);order_id:Mapped[str]=mapped_column(ForeignKey("orders.id",ondelete="CASCADE"),index=True);provider:Mapped[str]=mapped_column(String(80));provider_reference:Mapped[str|None]=mapped_column(String(255),unique=True);status:Mapped[str]=mapped_column(String(30),default="PENDING");amount_minor:Mapped[int]=mapped_column(BigInteger);currency:Mapped[str]=mapped_column(String(3));created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class Subscription(Base):
 __tablename__="subscriptions";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.id",ondelete="CASCADE"),index=True);client_id:Mapped[str]=mapped_column(ForeignKey("clients.id",ondelete="CASCADE"),index=True);plan_id:Mapped[str]=mapped_column(ForeignKey("plans.id"));status:Mapped[str]=mapped_column(String(30),default="ACTIVE");starts_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now);ends_at:Mapped[datetime]=mapped_column(DateTime(timezone=True));traffic_bytes:Mapped[int|None]=mapped_column(BigInteger)
class Wallet(Base):
 __tablename__="wallets";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.id",ondelete="CASCADE"),unique=True);balance_minor:Mapped[int]=mapped_column(BigInteger,default=0);currency:Mapped[str]=mapped_column(String(3),default="USD")
class WalletTransaction(Base):
 __tablename__="wallet_transactions";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);wallet_id:Mapped[str]=mapped_column(ForeignKey("wallets.id",ondelete="CASCADE"),index=True);amount_minor:Mapped[int]=mapped_column(BigInteger);kind:Mapped[str]=mapped_column(String(40));reference:Mapped[str|None]=mapped_column(String(255),unique=True);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class NodePeerCounter(Base):
 __tablename__="node_peer_counters"
 id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid)
 tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.id",ondelete="CASCADE"),index=True)
 node_id:Mapped[str]=mapped_column(ForeignKey("nodes.id",ondelete="CASCADE"),index=True)
 inbound_id:Mapped[str]=mapped_column(ForeignKey("inbounds.id",ondelete="CASCADE"),index=True)
 client_id:Mapped[str]=mapped_column(ForeignKey("clients.id",ondelete="CASCADE"),index=True)
 public_identifier:Mapped[str]=mapped_column(String(255))
 bytes_in:Mapped[int]=mapped_column(BigInteger,default=0)
 bytes_out:Mapped[int]=mapped_column(BigInteger,default=0)
 updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,onupdate=now)
 __table_args__=(UniqueConstraint("node_id","inbound_id","public_identifier"),)
class Job(Base):
 __tablename__="jobs";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);tenant_id:Mapped[str|None]=mapped_column(ForeignKey("tenants.id",ondelete="CASCADE"),index=True);kind:Mapped[str]=mapped_column(String(100));state:Mapped[str]=mapped_column(String(30),default="QUEUED");payload:Mapped[str]=mapped_column(Text,default="{}");attempts:Mapped[int]=mapped_column(Integer,default=0);run_after:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now);created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class AuditLog(Base):
 __tablename__="audit_logs";id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid);tenant_id:Mapped[str|None]=mapped_column(ForeignKey("tenants.id",ondelete="SET NULL"),index=True);actor_id:Mapped[str|None]=mapped_column(ForeignKey("admins.id",ondelete="SET NULL"));action:Mapped[str]=mapped_column(String(160));resource:Mapped[str]=mapped_column(String(100));resource_id:Mapped[str|None]=mapped_column(String(36));result:Mapped[str]=mapped_column(String(30));ip:Mapped[str|None]=mapped_column(String(64));user_agent:Mapped[str|None]=mapped_column(String(512));request_id:Mapped[str|None]=mapped_column(String(100));created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now);details:Mapped[str]=mapped_column(Text,default="{}")
Index("ix_sessions_client_last_seen","sessions.client_id","sessions.last_seen_at");Index("ix_traffic_client_last_seen","traffic_usage.client_id","traffic_usage.last_seen");Index("ix_audit_tenant_created","audit_logs.tenant_id","audit_logs.created_at")