<script setup lang="ts">
import{computed,onMounted,ref,watch}from"vue";
import{auth,nodes,inbounds,clients,traffic,audit,quotas,admins,configs,settings}from"./api";
const sections=[["dashboard","داشبورد","Dashboard"],["nodes","نودها","Nodes"],["inbounds","این‌باندها","Inbounds"],["clients","کلاینت‌ها","Clients"],["traffic","ترافیک و سهمیه","Traffic & Usage"],["admins","مدیران و RBAC","Managers & RBAC"],["audit","گزارش حسابرسی","Audit Logs"],["settings","تنظیمات","Settings"]];
const settingsData=ref<any>(null),settingsDraft=ref<any>(null),artifact=ref<any>(null),section=ref("dashboard"),lang=ref<"fa"|"en">("fa"),drawer=ref(false),email=ref(""),password=ref(""),mfaToken=ref(""),mfaCode=ref(""),loginError=ref(""),loading=ref(false),booting=ref(true),me=ref<any>(null),modal=ref<string|null>(null),notice=ref("");
const nodeRows=ref<any[]>([]),inboundRows=ref<any[]>([]),clientRows=ref<any[]>([]),adminRows=ref<any[]>([]),adminInboundRows=ref<any[]>([]),auditRows=ref<any[]>([]),trafficData=ref<any>({}),trafficBreakdown=ref<any[]>([]),quotaRows=ref<any[]>([]),trafficDays=ref(7),trafficSearch=ref(""),trafficProtocol=ref(""),trafficNode=ref(""),trafficInbound=ref(""),auditSearch=ref(""),auditActionFilter=ref(""),auditResultFilter=ref(""),auditDays=ref(30),auditPage=ref(1),auditPageSize=ref(10),clientDetail=ref<any>(null),clientDevices=ref<any[]>([]),artifactName=ref("client.conf");
const clientFilters=ref({search:"",status:"",protocol:"",inbound_id:"",online:""}),installCommand=ref(""),installNodeInfo=ref<any>(null);
const nodeForm=ref({name:"",address:"",agent_url:""}),inboundForm=ref({node_id:"",name:"",protocol:"wireguard",listen_port:51820,interface:"wg0",address:"10.10.0.1/24",network:"10.10.0.0/24",dns:"1.1.1.1"}),clientForm=ref({inbound_id:"",name:"",assigned_address:"10.10.0.2/32",expires_at:"",total_gb:"",daily_gb:"",monthly_gb:"",max_devices:"",warning_ratio:80}),adminForm=ref({email:"",password:"",role:"tenant_operator",tenant_id:"",inbound_ids:[] as string[],enabled:true,quota_gb:"",duration_days:""}),quotaForm=ref({client_id:"",total_bytes:"",daily_bytes:"",monthly_bytes:"",max_devices:"",warning_ratio:80});
const installArtifact=ref<any>(null),clientEditingId=ref<string|null>(null),inboundEditingId=ref<string|null>(null),adminEditingId=ref<string|null>(null),adminSearch=ref(""),adminRoleFilter=ref(""),adminStatusFilter=ref(""),adminPage=ref(1),adminPageSize=4;
const visibleSections=computed(()=>{if(me.value?.role==="representative")return sections.filter(x=>x[0]==="clients");if(me.value?.role==="tenant_operator")return sections.filter(x=>!["admins","settings"].includes(x[0]));return sections});
const allowedClientInbounds=computed(()=>me.value?.role==="representative"?adminInboundRows.value:inboundRows.value);
const filteredAdminRows=computed(()=>{
 const q=adminSearch.value.trim().toLowerCase();
 return adminRows.value.filter(a=>!["platform_owner","tenant_manager"].includes(a.role)).filter(a=>{
  const text=[a.email,a.role,adminRoleLabel(a.role)].join(" ").toLowerCase();
  return (!q||text.includes(q))&&(!adminRoleFilter.value||a.role===adminRoleFilter.value)&&(!adminStatusFilter.value||(adminStatusFilter.value==="active"?a.enabled:!a.enabled));
 });
});
const adminPageCount=computed(()=>Math.max(1,Math.ceil(filteredAdminRows.value.length/adminPageSize)));
const paginatedAdminRows=computed(()=>filteredAdminRows.value.slice((adminPage.value-1)*adminPageSize,adminPage.value*adminPageSize));
const adminPageStart=computed(()=>filteredAdminRows.value.length?((adminPage.value-1)*adminPageSize)+1:0);
const adminPageEnd=computed(()=>Math.min(adminPage.value*adminPageSize,filteredAdminRows.value.length));
watch([adminSearch,adminRoleFilter,adminStatusFilter],()=>{adminPage.value=1});
watch(adminPageCount,()=>{if(adminPage.value>adminPageCount.value)adminPage.value=adminPageCount.value});
const adminRoleLabel=(role:string)=>({tenant_operator:"اپراتور",representative:"نماینده"} as Record<string,string>)[role]||role;
const title=computed(()=>{const s=sections.find(x=>x[0]===section.value);return s?.[lang.value==="fa"?1:2]??(lang.value==="fa"?"داشبورد":"Dashboard")});
const dir=computed(()=>lang.value==="fa"?"rtl":"ltr");
const t=(fa:string,en:string)=>lang.value==="fa"?fa:en;
const nodeOnline=computed(()=>nodeRows.value.filter(n=>["ready","degraded","READY","DEGRADED"].includes(String(n.state||""))).length);
const nodeOffline=computed(()=>Math.max(0,nodeRows.value.length-nodeOnline.value));
const inboundActive=computed(()=>inboundRows.value.filter(x=>["active","ready","ACTIVE","READY"].includes(String(x.state||x.desired_state||""))).length);
const clientActive=computed(()=>clientRows.value.filter(x=>["ACTIVE","active"].includes(String(x.status||x.state||""))).length);
const nodeSearch=ref(""),nodeStateFilter=ref("");
const filteredNodeRows=computed(()=>nodeRows.value.filter(n=>{const q=nodeSearch.value.trim().toLowerCase();return(!q||[n.name,n.address,n.agent_url,n.id].join(" ").toLowerCase().includes(q))&&(!nodeStateFilter.value||String(n.state)===nodeStateFilter.value)}));
const nodeHealthy=computed(()=>nodeRows.value.filter(n=>["READY","DEGRADED"].includes(String(n.state))).length);
const inboundSearch=ref(""),inboundProtocolFilter=ref(""),inboundStateFilter=ref("");
const filteredInboundRows=computed(()=>inboundRows.value.filter(x=>{
 const q=inboundSearch.value.trim().toLowerCase();
 const text=[x.name,x.protocol,x.interface,x.address,x.network,x.node_id,x.id].join(" ").toLowerCase();
 const state=String(x.desired_state||x.state||"").toLowerCase();
 return (!q||text.includes(q))&&(!inboundProtocolFilter.value||String(x.protocol)===inboundProtocolFilter.value)&&(!inboundStateFilter.value||state===inboundStateFilter.value.toLowerCase());
}));
const inboundClientsCount=(id:string)=>clientRows.value.filter(x=>x.inbound_id===id&&x.status!=="REVOKED").length;
const inboundOnlineCount=(id:string)=>clientRows.value.filter(x=>x.inbound_id===id&&x.online).length;
const inboundDisabled=computed(()=>inboundRows.value.filter(x=>x.enabled===false||String(x.desired_state||"").toUpperCase()!=="ACTIVE").length);
const filteredClientRows=computed(()=>{const f=clientFilters.value;return clientRows.value.filter(x=>{const q=f.search.trim().toLowerCase();const text=[x.name,x.assigned_address,x.inbound_name,x.node_name].join(" ").toLowerCase();return(!q||text.includes(q))&&(!f.status||String(x.status).toLowerCase()===f.status.toLowerCase())&&(!f.protocol||String(x.protocol)===f.protocol)&&(!f.inbound_id||x.inbound_id===f.inbound_id)&&(!f.online||String(x.online)===f.online)})});
const clientTrafficTotal=computed(()=>clientRows.value.reduce((s,x)=>s+Number(x.total_traffic||0),0));
const clientOnlineCount=computed(()=>clientRows.value.filter(x=>x.online).length);
const clientExpiringCount=computed(()=>{const n=Date.now()+7*86400000;return clientRows.value.filter(x=>x.expires_at&&new Date(x.expires_at).getTime()<=n&&new Date(x.expires_at).getTime()>Date.now()&&x.status!=="REVOKED").length});
const clientQuotaWarnings=computed(()=>clientRows.value.filter(x=>x.quota_state==="WARNING"||x.quota_state==="LIMIT_REACHED").length);
const trafficTotal=computed(()=>Number(trafficData.value.total_bytes||0));
const trafficIn=computed(()=>Number(trafficData.value.bytes_in||0));
const trafficOut=computed(()=>Number(trafficData.value.bytes_out||0));
const trafficMax=computed(()=>Math.max(trafficIn.value,trafficOut.value,1));
const trafficInPct=computed(()=>Math.round(trafficIn.value/trafficMax.value*100));
const trafficOutPct=computed(()=>Math.round(trafficOut.value/trafficMax.value*100));
const recentActivity=computed(()=>auditRows.value.slice(0,5));
const formatBytes=(n:number)=>{if(!n)return "0 B";const u=["B","KB","MB","GB","TB","PB"];const i=Math.min(Math.floor(Math.log(n)/Math.log(1024)),u.length-1);return (n/Math.pow(1024,i)).toFixed(i?2:0)+" "+u[i]};
const trafficTotalLabel=computed(()=>formatBytes(trafficTotal.value));
const trafficInLabel=computed(()=>formatBytes(trafficIn.value));
const trafficOutLabel=computed(()=>formatBytes(trafficOut.value));
const filteredTrafficRows=computed(()=>trafficBreakdown.value.filter(x=>{const q=trafficSearch.value.trim().toLowerCase();return(!q||[x.client_name,x.client_id,x.node_id,x.inbound_id,x.protocol].join(" ").toLowerCase().includes(q))}));
const filteredAuditRows=computed(()=>{const q=auditSearch.value.trim().toLowerCase();const since=Date.now()-auditDays.value*86400000;return auditRows.value.filter(x=>{const text=[x.action,x.resource,x.resource_id,x.actor_email,x.ip,x.request_id].join(" ").toLowerCase();const ts=x.created_at?new Date(x.created_at).getTime():0;return(!q||text.includes(q))&&(!auditActionFilter.value||x.action===auditActionFilter.value)&&(!auditResultFilter.value||String(x.result).toLowerCase()===auditResultFilter.value.toLowerCase())&&(!ts||ts>=since)})});
const auditActions=computed(()=>[...new Set(auditRows.value.map(x=>x.action).filter(Boolean))]);
const auditPageCount=computed(()=>Math.max(1,Math.ceil(filteredAuditRows.value.length/auditPageSize.value)));
const paginatedAuditRows=computed(()=>filteredAuditRows.value.slice((auditPage.value-1)*auditPageSize.value,auditPage.value*auditPageSize.value));
const auditSuccessCount=computed(()=>filteredAuditRows.value.filter(x=>["success","ok"].includes(String(x.result).toLowerCase())).length);
const auditFailedCount=computed(()=>filteredAuditRows.value.length-auditSuccessCount.value);
const auditActorCount=computed(()=>new Set(filteredAuditRows.value.map(x=>x.actor_id||x.actor_email).filter(Boolean)).size);
const auditPageStart=computed(()=>filteredAuditRows.value.length?(auditPage.value-1)*auditPageSize.value+1:0);
const auditPageEnd=computed(()=>Math.min(auditPage.value*auditPageSize.value,filteredAuditRows.value.length));
const auditActionLabel=(a:string)=>({login:"ورود",node_create:"ایجاد نود",node_provision:"Provision نود",inbound_create:"ایجاد Inbound",inbound_sync:"Sync Inbound",client_create:"ایجاد Client",client_revoke:"Revoke Client",quota_set:"تنظیم سهمیه",admin_create:"ایجاد مدیر",admin_update:"ویرایش مدیر",admin_disable:"غیرفعال‌سازی مدیر",admin_delete:"حذف مدیر"} as Record<string,string>)[a]||a;
const auditResultLabel=(r:any)=>{const v=String(r||"").toLowerCase();return ["success","ok"].includes(v)?"موفق":"ناموفق"};
const quotaLimitCount=computed(()=>quotaRows.value.filter(x=>x.state==="LIMIT_REACHED").length);
const quotaWarningCount=computed(()=>quotaRows.value.filter(x=>x.state==="WARNING").length);
const quotaNormalCount=computed(()=>quotaRows.value.filter(x=>x.state==="NORMAL").length);
const activityLabel=(x:any)=>{const a=String(x?.action||"Activity");return ({login:"ورود کاربر",node_provision:"Provision نود",node_create:"ایجاد نود",inbound_create:"ایجاد Inbound",inbound_sync:"Sync Inbound",client_create:"ایجاد Client",client_revoke:"Revoke Client",quota_set:"تنظیم سهمیه"} as Record<string,string>)[a]||a};
const activityTone=(x:any)=>{const a=String(x?.action||"");if(a.includes("revoke")||String(x?.result||"").toLowerCase().includes("fail"))return "danger";if(a.includes("provision")||a.includes("create"))return "primary";return "success"};
watch([auditSearch,auditActionFilter,auditResultFilter,auditDays],()=>auditPage.value=1);
const refreshDashboard=()=>load();
async function refreshTraffic(){
 loading.value=true;
 try{
  await traffic.collect();
  trafficData.value=await traffic.summary(trafficDays.value);
  trafficBreakdown.value=await traffic.breakdown(trafficDays.value);
  quotaRows.value=await quotas.overview();
  notice.value="ترافیک و سهمیه بروزرسانی شد";
 }catch(e){notice.value=e instanceof Error?e.message:"بروزرسانی ترافیک ناموفق"}finally{loading.value=false}
}
async function loadTrafficView(){
 try{
  trafficData.value=await traffic.summary(trafficDays.value);
  const params=new URLSearchParams();
  if(trafficProtocol.value)params.set("protocol",trafficProtocol.value);
  if(trafficNode.value)params.set("node_id",trafficNode.value);
  if(trafficInbound.value)params.set("inbound_id",trafficInbound.value);
  trafficBreakdown.value=await traffic.breakdown(trafficDays.value,params.toString());
  quotaRows.value=await quotas.overview();
 }catch(e){notice.value=e instanceof Error?e.message:"خطای Traffic API"}
}
async function load(){loading.value=true;try{
 me.value=await auth.me();
 const isRep=me.value.role==="representative";
 const[n,i,c,t,auditData,q]=await Promise.all([
  nodes.list(),inbounds.list(),clients.list(),
  isRep?Promise.resolve({total_bytes:0,today_bytes:0,month_bytes:0}):traffic.summary(trafficDays.value),
  isRep?Promise.resolve([]):audit.list(),
  isRep?Promise.resolve([]):quotas.overview()
 ]);
 nodeRows.value=n;inboundRows.value=i;clientRows.value=c;trafficData.value=t;quotaRows.value=q;auditRows.value=auditData;
 if(me.value.role!=="tenant_operator"&&me.value.role!=="representative"&&me.value.tenant_id){try{const sr=await settings.get();settingsData.value=sr;settingsDraft.value={...sr.settings}}catch(e){notice.value=e instanceof Error?e.message:"خطای Settings API"}}
 if(me.value.role!=="tenant_operator"&&me.value.role!=="representative"){adminRows.value=await admins.list();adminInboundRows.value=await admins.inbounds()}
 if(isRep){adminInboundRows.value=await admins.myInbounds();section.value="clients"}
}catch(e){if(localStorage.getItem("primevpn_access"))loginError.value=e instanceof Error?e.message:"خطای API"}finally{loading.value=false;booting.value=false}}
async function login(){loginError.value="";loading.value=true;try{const r=await auth.login(email.value,password.value);if(r.mfa_required){mfaToken.value=r.mfa_token;modal.value="mfa";return}localStorage.setItem("primevpn_access",r.access_token);await load()}catch(e){loginError.value=e instanceof Error?e.message:"ورود ناموفق"}finally{loading.value=false}}
async function verifyMfa(){try{const r=await auth.mfaVerify(mfaToken.value,mfaCode.value);localStorage.setItem("primevpn_access",r.access_token);modal.value=null;await load()}catch(e){loginError.value=e instanceof Error?e.message:"کد MFA نامعتبر"}}
async function act(fn:()=>Promise<any>,success="انجام شد"){try{await fn();notice.value=success;modal.value=null;await load()}catch(e){notice.value=e instanceof Error?e.message:"خطا"}}
function clientFilename(protocol:string,name:string){const safe=name.replace(/[^a-zA-Z0-9._-]+/g,"-").replace(/^-+|-+$/g,"")||"client";return safe+(protocol==="openvpn"?".ovpn":".conf")}
function downloadArtifact(){if(!artifact.value?.payload)return;const blob=new Blob([artifact.value.payload],{type:"text/plain;charset=utf-8"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=artifactName.value;a.click();URL.revokeObjectURL(url);notice.value="فایل کانفیگ دانلود شد"}
async function issueConfig(id:string,autoDownload=false){try{const c=await clients.credential(id);artifact.value=await configs.download(c.artifact_id);const row=clientRows.value.find(x=>x.id===id);artifactName.value=clientFilename(String(artifact.value?.protocol||row?.protocol||"wireguard"),row?.name||"client");modal.value="artifact";if(autoDownload)downloadArtifact()}catch(e){notice.value=e instanceof Error?e.message:"خطا در ساخت Config"}}
async function createClient(){loading.value=true;try{const f=clientForm.value;const gb=(v:string)=>v&&Number(v)>0?Math.round(Number(v)*1024*1024*1024):null;const created=await clients.create({inbound_id:f.inbound_id,name:f.name,assigned_address:f.assigned_address,expires_at:f.expires_at?new Date(f.expires_at).toISOString():null,total_bytes:gb(f.total_gb),daily_bytes:gb(f.daily_gb),monthly_bytes:gb(f.monthly_gb),max_devices:f.max_devices?Number(f.max_devices):null,warning_ratio:Number(f.warning_ratio||80)});modal.value=null;await load();await issueConfig(created.id,true);notice.value="کلاینت ساخته شد و فایل کانفیگ آماده دانلود است"}catch(e){notice.value=e instanceof Error?e.message:"ساخت کلاینت ناموفق"}finally{loading.value=false}}
function openAdminCreate(){adminEditingId.value=null;adminForm.value={email:"",password:"",role:"tenant_operator",tenant_id:me.value?.tenant_id||"",inbound_ids:[],enabled:true,quota_gb:"",duration_days:""};modal.value="admin"}
function openAdminEdit(a:any){adminEditingId.value=a.id;adminForm.value={email:a.email,password:"",role:a.role,tenant_id:a.tenant_id||"",inbound_ids:[...(a.inbound_ids||[])],enabled:!!a.enabled,quota_gb:a.traffic_limit_bytes?String((a.traffic_limit_bytes/1073741824).toFixed(2)):"0",duration_days:String(a.quota_duration_days||0)};modal.value="admin"}
async function saveAdmin(){loading.value=true;const editing=!!adminEditingId.value;try{const f=adminForm.value;const body:any={role:f.role,inbound_ids:f.role==="representative"?f.inbound_ids:[],enabled:f.enabled,quota_gb:f.quota_gb?Number(f.quota_gb):0,duration_days:f.duration_days?Number(f.duration_days):0};if(!editing){body.email=f.email;body.password=f.password;if(me.value?.role==="platform_owner")body.tenant_id=f.tenant_id}else if(f.password)body.password=f.password;if(editing)await admins.update(adminEditingId.value!,body);else await admins.create(body);modal.value=null;adminEditingId.value=null;notice.value=editing?"مدیر بروزرسانی شد":"مدیر ساخته شد";await load()}catch(e){notice.value=e instanceof Error?e.message:"عملیات مدیر ناموفق بود"}finally{loading.value=false}}
async function disableAdmin(a:any){if(!confirm("این مدیر غیرفعال شود؟"))return;try{await admins.disable(a.id);notice.value="مدیر غیرفعال شد";await load()}catch(e){notice.value=e instanceof Error?e.message:"خطا"}}
async function deleteAdmin(a:any){if(!confirm(`حذف دائمی مدیر ${a.email}؟ این عملیات قابل بازگشت نیست.`))return;try{await admins.remove(a.id);notice.value="مدیر حذف شد";await load()}catch(e){notice.value=e instanceof Error?e.message:"حذف مدیر ناموفق بود"}}
function resetClientForm(){clientEditingId.value=null;clientForm.value={inbound_id:"",name:"",assigned_address:"10.10.0.2/32",expires_at:"",total_gb:"",daily_gb:"",monthly_gb:"",max_devices:"",warning_ratio:80}}
function openClientEdit(x:any){clientEditingId.value=x.id;clientForm.value={inbound_id:x.inbound_id,name:x.name,assigned_address:x.assigned_address,expires_at:x.expires_at?new Date(x.expires_at).toISOString().slice(0,16):"",total_gb:x.quota_total?String((x.quota_total/1073741824).toFixed(2)):"",daily_gb:x.quota_daily?String((x.quota_daily/1073741824).toFixed(2)):"",monthly_gb:x.quota_monthly?String((x.quota_monthly/1073741824).toFixed(2)):"",max_devices:x.max_devices?String(x.max_devices):"",warning_ratio:x.quota_warning_ratio||80};modal.value="client-edit"}
async function saveClientEdit(){if(!clientEditingId.value)return;loading.value=true;try{const f=clientForm.value;const gb=(v:string)=>v&&Number(v)>0?Math.round(Number(v)*1024*1024*1024):undefined;await clients.update(clientEditingId.value,{name:f.name,expires_at:f.expires_at?new Date(f.expires_at).toISOString():null,total_bytes:gb(f.total_gb),daily_bytes:gb(f.daily_gb),monthly_bytes:gb(f.monthly_gb),max_devices:f.max_devices?Number(f.max_devices):undefined,warning_ratio:Number(f.warning_ratio||80)});notice.value="اطلاعات کلاینت بروزرسانی شد";modal.value=null;await load()}catch(e){notice.value=e instanceof Error?e.message:"بروزرسانی ناموفق"}finally{loading.value=false}}
function openNodeDetail(n:any){clientDetail.value={...n};clientDevices.value=[];modal.value="node-detail"}
function resetInboundForm(){inboundEditingId.value=null;inboundForm.value={node_id:"",name:"",protocol:"wireguard",listen_port:51820,interface:"wg0",address:"10.10.0.1/24",network:"10.10.0.0/24",dns:"1.1.1.1"}}
function openInboundEdit(x:any){inboundEditingId.value=x.id;inboundForm.value={node_id:x.node_id,name:x.name,protocol:x.protocol,listen_port:x.listen_port,interface:x.interface,address:x.address,network:x.network,dns:x.dns||"1.1.1.1"};modal.value="inbound"}
function openInboundDetail(x:any){clientDetail.value={...x};modal.value="inbound-detail"}
async function saveInbound(){loading.value=true;try{if(inboundEditingId.value)await inbounds.update(inboundEditingId.value,inboundForm.value);else await inbounds.create(inboundForm.value);notice.value=inboundEditingId.value?"Inbound بروزرسانی شد":"Inbound ساخته شد";modal.value=null;resetInboundForm();await load()}catch(e){notice.value=e instanceof Error?e.message:"عملیات Inbound ناموفق"}finally{loading.value=false}}
async function openClientDetail(x:any){clientDetail.value=x;clientDevices.value=await clients.devices(x.id);modal.value="client-detail"}
async function revokeClient(id:string){if(!window.confirm("این کلاینت و تمام Credentialهای فعال آن revoke شود؟"))return;await act(()=>clients.revoke(id),"کلاینت revoke شد")}
async function copyArtifact(){if(artifact.value?.payload)await navigator.clipboard.writeText(artifact.value.payload);notice.value="Config کپی شد"}
async function createInstallToken(){try{const r=await nodes.installToken({name:nodeForm.value.name,address:nodeForm.value.address});installCommand.value=r.install_command;installNodeInfo.value=r;modal.value="node-install"}catch(e){notice.value=e instanceof Error?e.message:"ساخت توکن نصب ناموفق"}}
async function copyInstallCommand(){if(installCommand.value)await navigator.clipboard.writeText(installCommand.value);notice.value="دستور نصب کپی شد"}
async function provision(id:string){try{const r=await nodes.provision(id);notice.value=r.bootstrap_token?"Bootstrap token ساخته شد؛ برای نصب Agent استفاده کن":"Provisioning ثبت شد";if(r.bootstrap_token)notice.value=`Bootstrap Token: ${r.bootstrap_token}`;modal.value=null;await load()}catch(e){notice.value=e instanceof Error?e.message:"Provisioning ناموفق"}}
async function deleteNode(n:any){if(me.value.role==="tenant_operator")return;if(!window.confirm(`نود "${n.name}" حذف شود؟ این کار فقط نودی را حذف می‌کند که Inbound نداشته باشد.`))return;await act(()=>nodes.remove(n.id),"نود حذف شد")}
function goSection(id:string){section.value=id;drawer.value=false;if(id==="traffic")loadTrafficView()}
function logout(){localStorage.removeItem("primevpn_access");me.value=null}async function saveSettings(){if(!settingsDraft.value)return;loading.value=true;try{const r=await settings.update(settingsDraft.value);settingsData.value={...(settingsData.value||{}),settings:r.settings};settingsDraft.value={...r.settings};notice.value="تنظیمات با موفقیت ذخیره شد"}catch(e){notice.value=e instanceof Error?e.message:"ذخیره تنظیمات ناموفق"}finally{loading.value=false}}
function resetSettings(){if(settingsData.value?.settings)settingsDraft.value={...settingsData.value.settings}}

onMounted(load);
</script>
<template>
<div v-if="booting" class="app-shell"><main class="main"><div class="panel page"><div class="empty">در حال اتصال به PRIMEVPN Control Plane…</div></div></main></div>
<div v-else-if="!me" class="login-shell"><div class="login-card"><div class="brand"><span class="brand-mark">P</span><div><b>PRIMEVPN</b><small>Control Plane v1.0.0</small></div></div><h1>ورود به پنل</h1><p>مدیریت امن Node، Inbound، Client و Traffic</p><input v-model="email" type="email" placeholder="Email"><input v-model="password" type="password" placeholder="Password" @keyup.enter="login"><button class="primary wide" :disabled="loading" @click="login">{{loading?"در حال ورود…":"ورود"}}</button><div v-if="loginError" class="error-box">{{loginError}}</div></div></div>
<div v-else class="app-shell" :dir="dir">
<div v-if="drawer" class="drawer-backdrop" @click="drawer=false"></div>
<aside class="sidebar" :class="{open:drawer}"><div class="brand"><span class="brand-mark">P</span><div><b>PRIMEVPN</b><small>Control Plane v1.0.0</small></div></div><nav><button v-for="s in visibleSections" :key="s[0]" :class="{active:section===s[0]}" @click.stop="goSection(s[0])"><span class="nav-icon">{{["⌂","♙","▤","◎","▣","◈","⌁","⚙"][sections.indexOf(s)]}}</span><span>{{s[lang==="fa"?1:2]}}</span><small>{{s[lang==="fa"?2:1]}}</small></button></nav><div class="sidebar-foot"><i></i>{{me.email}}<button class="icon" @click="logout">خروج</button></div></aside>
<main class="main"><header><button class="mobile-menu" @click="drawer=true">☰</button><div class="top-brand"><span class="brand-mark">P</span><div><b>PRIME<span>VPN</span></b><small>Secure · Fast · Global</small></div></div><div class="header-spacer"></div><div class="account-pill"><i></i><div><b>{{me.role}}</b><small>Tenant</small></div><span>●</span></div><div class="language"><button :class="{on:lang==='fa'}" @click="lang='fa'">فارسی</button><button :class="{on:lang==='en'}" @click="lang='en'">English</button></div></header><div v-if="notice" class="notice" @click="notice=''">{{notice}}</div>
<div v-if="loading" class="panel"><div class="empty">در حال دریافت داده…</div></div>
<section v-else-if="section==='dashboard'" class="dashboard-home">
<div class="dashboard-toolbar"><div><span class="eyebrow">PRIMEVPN CONTROL PLANE</span><h1>{{t("نمای کلی سیستم","System Overview")}}</h1><p>{{t("وضعیت لحظه‌ای نودها، اینباندها، کلاینت‌ها و مصرف ترافیک","Live overview of nodes, inbounds, clients and traffic")}}</p></div><button class="refresh-btn" :disabled="loading" @click="refreshDashboard">↻ {{t("بروزرسانی","Refresh")}}</button></div>
<div class="welcome-row"><div><small>{{t("خوش آمدید","Welcome back")}}</small><h2>{{me.email}}</h2><div class="service-status"><i></i><b>{{t("Control Plane آنلاین است","Control Plane is online")}}</b><small>API</small></div></div><div class="hero-shield">P</div></div>
<div class="stats dashboard-stats">
<article><span class="stat-icon users">♟</span><small>{{t("کل کلاینت‌ها","Total Clients")}}</small><strong>{{clientRows.length}}</strong><em class="neutral">{{clientActive}} {{t("فعال","active")}}</em></article>
<article><span class="stat-icon nodes">▤</span><small>{{t("نودهای آنلاین","Online Nodes")}}</small><strong>{{nodeOnline}}<small class="of-total"> / {{nodeRows.length}}</small></strong><em class="neutral">{{nodeOffline}} {{t("نود خارج از دسترس","offline")}}</em></article>
<article><span class="stat-icon plans">◎</span><small>{{t("اینباند‌های فعال","Active Inbounds")}}</small><strong>{{inboundActive}}<small class="of-total"> / {{inboundRows.length}}</small></strong><em class="neutral">{{inboundRows.length-inboundActive}} {{t("غیرفعال","inactive")}}</em></article>
<article><span class="stat-icon traffic">⌁</span><small>{{t("کل ترافیک","Total Traffic")}}</small><strong>{{trafficTotalLabel}}</strong><em class="neutral">IN {{trafficInLabel}} · OUT {{trafficOutLabel}}</em></article>
</div>
<div class="dashboard-grid">
<div class="panel traffic-card"><div class="panel-head"><div><h2>{{t("مصرف ترافیک","Traffic Usage")}}</h2><small>{{t("بر اساس داده‌های ثبت‌شده","Based on recorded usage")}}</small></div><span class="live-badge"><i></i>{{t("زنده","Live")}}</span></div>
<div class="traffic-total">{{trafficTotalLabel}}</div>
<div class="traffic-bars"><div class="traffic-row"><span>IN</span><div class="traffic-track"><b :style="{ width: trafficInPct + '%' }"></b></div><strong>{{trafficInLabel}}</strong></div><div class="traffic-row"><span>OUT</span><div class="traffic-track out"><b  :style="{ width: trafficOutPct + '%' }"></b></div><strong>{{trafficOutLabel}}</strong></div></div>
<div class="traffic-foot"><span>{{t("دریافت","Download")}} {{trafficInPct}}%</span><span>{{t("ارسال","Upload")}} {{trafficOutPct}}%</span></div></div>
<div class="panel health-card"><div class="panel-head"><div><h2>{{t("سلامت زیرساخت","Infrastructure Health")}}</h2><small>Nodes · Inbounds · Clients</small></div></div>
<div class="health-row"><span class="health-icon nodes">▤</span><div><b>{{t("نودها","Nodes")}}</b><small>{{nodeOnline}} {{t("آنلاین","online")}} · {{nodeOffline}} {{t("خارج از دسترس","offline")}}</small></div><strong :class="nodeOffline ? 'bad' : ''">{{nodeOffline ? t("نیازمند بررسی","Attention") : t("سالم","Healthy")}}</strong></div>
<div class="health-row"><span class="health-icon plans">◎</span><div><b>{{t("اینباند‌ها","Inbounds")}}</b><small>{{inboundActive}} {{t("فعال","active")}} · {{inboundRows.length - inboundActive}} {{t("غیرفعال","inactive")}}</small></div><strong :class="inboundRows.length - inboundActive ? 'bad' : ''">{{inboundRows.length - inboundActive ? t("بررسی شود","Review") : t("سالم","Healthy")}}</strong></div>
<div class="health-row"><span class="health-icon users">♟</span><div><b>{{t("کلاینت‌ها","Clients")}}</b><small>{{clientActive}} {{t("فعال","active")}} · {{clientRows.length-clientActive}} {{t("Revoke شده","revoked")}}</small></div><strong>{{t("آماده","Ready")}}</strong></div>
</div>
</div>
<div class="dashboard-grid lower"><div class="panel activity-card"><div class="panel-head"><div><h2>{{t("فعالیت‌های اخیر","Recent Activity")}}</h2><small>Audit Logs</small></div><button class="link" @click="goSection('audit')">{{t("مشاهده همه","View all")}} ›</button></div>
<div v-if="recentActivity.length" class="activity"><div v-for="x in recentActivity" :key="x.id"><span class="activity-icon" :class="activityTone(x)">{{activityTone(x)==='danger'?'!':activityTone(x)==='primary'?'◆':'✓'}}</span><div><b>{{activityLabel(x)}}</b><small>{{x.resource||x.actor_email||me.role}}</small></div><time>{{x.created_at}}</time><i :class="{danger:activityTone(x)==='danger'}"></i></div></div><div v-else class="dashboard-empty">{{t("هنوز فعالیتی ثبت نشده است","No activity has been recorded yet")}}</div></div>
<div class="panel quick-card"><div class="panel-head"><div><h2>{{t("دسترسی سریع","Quick Actions")}}</h2><small>Quick Actions</small></div></div><button @click="goSection('nodes')"><span>▤</span>{{t("مدیریت نودها","Manage Nodes")}} <b>›</b></button><button @click="goSection('inbounds')"><span>◎</span>{{t("مدیریت اینباند‌ها","Manage Inbounds")}} <b>›</b></button><button @click="goSection('clients')"><span>♟</span>{{t("مدیریت کلاینت‌ها","Manage Clients")}} <b>›</b></button><button @click="goSection('traffic')"><span>⌁</span>{{t("ترافیک و سهمیه","Traffic & Quota")}} <b>›</b></button></div></div>
<div class="dashboard-foot"><span>PRIMEVPN v1.0.0</span><span>{{t("آخرین بروزرسانی با Refresh انجام می‌شود","Use Refresh to fetch the latest control-plane data")}}</span></div>
</section>
<section v-else-if="section==='nodes'"><div class="nodes-page">
<div class="nodes-head"><div><span class="eyebrow">INFRASTRUCTURE MANAGEMENT</span><h1>نودها</h1><p>مدیریت VPS، اتصال Agent، سلامت سرویس و ظرفیت زیرساخت VPN</p></div><button v-if="me.role!=='tenant_operator'" class="primary" @click="modal='node'">+ نود جدید</button></div>
<div class="stats node-stats"><article><small>کل نودها</small><strong>{{nodeRows.length}}</strong><em>Infrastructure</em></article><article><small>آنلاین</small><strong>{{nodeOnline}}</strong><em>READY / DEGRADED</em></article><article><small>آفلاین</small><strong>{{nodeOffline}}</strong><em>نیازمند بررسی</em></article><article><small>Inbound فعال</small><strong>{{inboundActive}}</strong><em>روی کل نودها</em></article></div>
<div class="panel node-filters"><div class="filter-grid node-filter-grid"><input v-model="nodeSearch" placeholder="جستجو نام، IP یا Agent URL"><select v-model="nodeStateFilter"><option value="">همه وضعیت‌ها</option><option value="READY">READY</option><option value="DEGRADED">DEGRADED</option><option value="INSTALLING">INSTALLING</option><option value="PROVISION_FAILED">PROVISION FAILED</option><option value="DISABLED">DISABLED</option></select><button class="icon" @click="nodeSearch='';nodeStateFilter=''">پاک کردن فیلتر</button></div></div>
<div class="node-grid"><article v-for="n in filteredNodeRows" :key="n.id" class="node-card"><div class="node-card-head"><div><span class="node-icon">⌁</span><div class="node-title"><b>{{n.name}}</b><small>{{n.id}}</small></div></div><span class="node-state" :class="String(n.state||'').toLowerCase()"><i></i>{{n.state}}</span></div>
<div class="node-main"><div><small>VPS / Address</small><b>{{n.address}}</b></div><div><small>Agent</small><b>{{n.agent_url||'ثبت نشده'}}</b></div><div><small>آخرین ارتباط</small><b>{{n.last_seen_at?new Date(n.last_seen_at).toLocaleString('fa-IR'):'هنوز ثبت نشده'}}</b></div><div><small>Capabilities</small><b>{{n.capabilities?Object.keys(n.capabilities).join(' · '):'—'}}</b></div></div>
<div class="node-health"><span><i :class="{ok:n.state==='READY'||n.state==='DEGRADED'}"></i>Control Plane</span><span><i :class="{ok:!!n.agent_url}"></i>Agent</span><span><i :class="{ok:n.last_seen_at}"></i>Heartbeat</span></div>
<div class="node-card-actions"><button v-if="me.role!=='tenant_operator'" class="icon" @click="provision(n.id)">Provision / Sync</button><button class="icon" @click="openNodeDetail(n)">جزئیات</button><button v-if="me.role!=='tenant_operator'" class="icon danger-btn" @click="deleteNode(n)">حذف نود</button></div></article><div v-if="!filteredNodeRows.length" class="empty node-empty">نودی با این فیلتر پیدا نشد.</div></div>
</div></section>
<section v-else-if="section==='inbounds'"><div class="inbounds-page">
<div class="inbounds-head"><div><span class="eyebrow">INBOUND MANAGEMENT</span><h1>این‌باندها</h1><p>مدیریت WireGuard، AmneziaWG و OpenVPN؛ وضعیت، پورت، کلاینت‌ها و Sync هر Inbound</p></div><button v-if="me.role!=='tenant_operator'" class="primary" @click="resetInboundForm();modal='inbound'">+ اینباند جدید</button></div>
<div class="stats inbound-stats"><article><span class="stat-icon plans">◎</span><small>کل اینباندها</small><strong>{{inboundRows.length}}</strong><em>{{inboundRows.length-inboundDisabled}} فعال</em></article><article><span class="stat-icon nodes">▤</span><small>WireGuard / AWG</small><strong>{{inboundRows.filter(x=>x.protocol==='wireguard'||x.protocol==='amneziawg').length}}</strong><em>VPN tunnels</em></article><article><span class="stat-icon traffic">⌁</span><small>OpenVPN</small><strong>{{inboundRows.filter(x=>x.protocol==='openvpn').length}}</strong><em>UDP / TLS</em></article><article><span class="stat-icon users">♟</span><small>کلاینت‌های متصل</small><strong>{{clientOnlineCount}}</strong><em>Session آنلاین</em></article></div>
<div class="panel inbound-filters"><div class="filter-grid inbound-filter-grid"><input v-model="inboundSearch" placeholder="جستجو نام، Protocol، Interface، IP یا Network"><select v-model="inboundProtocolFilter"><option value="">همه پروتکل‌ها</option><option value="wireguard">WireGuard</option><option value="amneziawg">AmneziaWG</option><option value="openvpn">OpenVPN</option></select><select v-model="inboundStateFilter"><option value="">همه وضعیت‌ها</option><option value="active">ACTIVE</option><option value="ready">READY</option><option value="disabled">DISABLED</option></select><button class="icon" @click="inboundSearch='';inboundProtocolFilter='';inboundStateFilter=''">پاک کردن فیلتر</button></div></div>
<div class="inbound-grid"><article v-for="x in filteredInboundRows" :key="x.id" class="inbound-card">
<div class="inbound-card-head"><div><span class="inbound-icon" :class="String(x.protocol).toLowerCase()">{{x.protocol==='openvpn'?'O':'W'}}</span><div><b>{{x.name}}</b><small>{{x.protocol}}</small></div></div><span class="inbound-state" :class="String(x.desired_state||x.state||'').toLowerCase()"><i></i>{{x.desired_state||x.state||'UNKNOWN'}}</span></div>
<div class="inbound-meta"><div><small>Port</small><b>{{x.listen_port}}</b></div><div><small>Interface</small><b>{{x.interface}}</b></div><div><small>Address</small><b>{{x.address}}</b></div><div><small>Network</small><b>{{x.network}}</b></div></div>
<div class="inbound-usage"><div><span><b>{{inboundClientsCount(x.id)}}</b><small>کلاینت</small></span><span><b>{{inboundOnlineCount(x.id)}}</b><small>آنلاین</small></span><span><b>{{x.enabled===false?'خاموش':'فعال'}}</b><small>Runtime</small></span></div><div class="inbound-node"><small>Node ID</small><b>{{x.node_id}}</b></div></div>
<div class="inbound-actions"><button class="icon" @click="openInboundDetail(x)">جزئیات</button><button class="icon" @click="act(()=>inbounds.sync(x.id),'Inbound synced')">Sync</button><button v-if="me.role!=='tenant_operator'" class="icon" @click="openInboundEdit(x)">ویرایش</button><button v-if="me.role!=='tenant_operator'" class="icon danger-btn" @click="act(()=>inbounds.remove(x.id),'Inbound removed')">Delete</button></div>
</article><div v-if="!filteredInboundRows.length" class="panel empty inbound-empty">اینباندی با این فیلتر پیدا نشد.</div></div>
</div></section>
<section v-else-if="section==='clients'"><div class="clients-page">
<div class="clients-head"><div><span class="eyebrow">CLIENT MANAGEMENT</span><h1>کلاینت‌ها</h1><p>ساخت، سهمیه، زمان انقضا، ترافیک، دستگاه و فایل کانفیگ هر کلاینت</p></div><button v-if="me.role!=='tenant_operator'" class="primary" @click="resetClientForm();modal='client'">+ کلاینت جدید</button></div>
<div class="stats client-stats"><article><small>کل کلاینت‌ها</small><strong>{{clientRows.length}}</strong><em>{{clientActive}} فعال</em></article><article><small>آنلاین</small><strong>{{clientOnlineCount}}</strong><em>Session فعال</em></article><article><small>ترافیک کل</small><strong>{{formatBytes(clientTrafficTotal)}}</strong><em>IN + OUT</em></article><article><small>نیازمند بررسی</small><strong>{{clientQuotaWarnings+clientExpiringCount}}</strong><em>{{clientQuotaWarnings}} سهمیه · {{clientExpiringCount}} انقضا</em></article></div>
<div class="panel client-filters"><div class="filter-grid"><input v-model="clientFilters.search" placeholder="جستجو نام، IP، Inbound یا Node"><select v-model="clientFilters.status"><option value="">همه وضعیت‌ها</option><option value="ACTIVE">فعال</option><option value="EXPIRED">منقضی</option><option value="REVOKED">Revoke</option><option value="SUSPENDED">معلق</option></select><select v-model="clientFilters.protocol"><option value="">همه پروتکل‌ها</option><option value="wireguard">WireGuard</option><option value="amneziawg">AmneziaWG</option><option value="openvpn">OpenVPN</option></select><select v-model="clientFilters.inbound_id"><option value="">همه Inboundها</option><option v-for="i in inboundRows" :value="i.id">{{i.name}} · {{i.protocol}}</option></select><select v-model="clientFilters.online"><option value="">همه اتصال‌ها</option><option value="true">آنلاین</option><option value="false">آفلاین</option></select><button class="icon" @click="clientFilters={search:'',status:'',protocol:'',inbound_id:'',online:''}">پاک کردن فیلتر</button></div></div>
<div class="panel page client-table-panel"><div class="table client-table"><div class="tr th"><span>کلاینت</span><span>Inbound / Node</span><span>IP</span><span>ترافیک IN / OUT</span><span>سهمیه / زمان</span><span>وضعیت</span><span>عملیات</span></div><div v-if="filteredClientRows.length===0" class="empty">کلاینتی با این فیلتر پیدا نشد.</div><div v-for="x in filteredClientRows" :key="x.id" class="tr client-row"><span><b>{{x.name}}</b><small>{{x.protocol}} · {{x.devices_count}} device</small></span><span><b>{{x.inbound_name}}</b><small>{{x.node_name}} : {{x.listen_port}}</small></span><span>{{x.assigned_address}}</span><span><b>↓ {{formatBytes(x.traffic_in)}}</b><small>↑ {{formatBytes(x.traffic_out)}}</small></span><span><b>{{x.quota_total?formatBytes(x.quota_used)+" / "+formatBytes(x.quota_total):"بدون سقف"}}</b><small>{{x.expires_at?new Date(x.expires_at).toLocaleString('fa-IR'):"بدون انقضا"}}</small></span><span><i class="status-dot" :class="{online:x.online}"></i>{{x.online?'آنلاین':x.status}}</span><span class="row-actions"><button class="icon" @click="openClientDetail(x)">جزئیات</button><button class="icon" @click="issueConfig(x.id)">دانلود</button><button class="icon" @click="openClientEdit(x)" :disabled="x.status==='REVOKED'">ویرایش</button><button v-if="x.status!=='REVOKED'" class="icon danger-btn" @click="revokeClient(x.id)">Revoke</button></span></div></div></div>
</div></section>
<section v-else-if="section==='traffic'"><div class="traffic-page">
<div class="traffic-page-head"><div><span class="eyebrow">TRAFFIC & QUOTAS</span><h1>ترافیک و سهمیه</h1><p>مانیتورینگ مصرف، تفکیک کلاینت‌ها و کنترل سهمیه روزانه، ماهانه و کل</p></div><div class="traffic-head-actions"><select v-model.number="trafficDays" @change="loadTrafficView"><option :value="1">24 ساعت</option><option :value="7">۷ روز</option><option :value="30">۳۰ روز</option><option :value="90">۹۰ روز</option></select><button v-if="me.role!=='tenant_operator'" class="refresh-btn" @click="refreshTraffic">↻ جمع‌آوری و بروزرسانی</button></div></div>
<div class="stats traffic-stats"><article><small>کل مصرف</small><strong>{{trafficTotalLabel}}</strong><em>IN + OUT</em></article><article><small>دریافت</small><strong>{{trafficInLabel}}</strong><em>Download</em></article><article><small>ارسال</small><strong>{{trafficOutLabel}}</strong><em>Upload</em></article><article><small>مصرف این ماه</small><strong>{{formatBytes(trafficData.month_bytes||0)}}</strong><em>Snapshot based</em></article></div>
<div class="panel traffic-filter-panel"><div class="traffic-filter-grid"><input v-model="trafficSearch" placeholder="جستجو Client / Node / Inbound"><select v-model="trafficProtocol" @change="loadTrafficView"><option value="">همه پروتکل‌ها</option><option value="wireguard">WireGuard</option><option value="amneziawg">AmneziaWG</option><option value="openvpn">OpenVPN</option></select><select v-model="trafficNode" @change="loadTrafficView"><option value="">همه Nodeها</option><option v-for="n in nodeRows" :value="n.id">{{n.name}}</option></select><select v-model="trafficInbound" @change="loadTrafficView"><option value="">همه Inboundها</option><option v-for="i in inboundRows" :value="i.id">{{i.name}}</option></select><button class="icon" @click="trafficSearch='';trafficProtocol='';trafficNode='';trafficInbound='';loadTrafficView()">پاک کردن</button></div></div>
<div class="grid2 traffic-main-grid"><div class="panel"><div class="panel-head"><div><h2>مصرف به تفکیک Client</h2><small>بر اساس TrafficUsage فعلی</small></div><span class="live-badge">{{filteredTrafficRows.length}} رکورد</span></div><div class="traffic-usage-table"><div class="traffic-usage-row traffic-usage-head"><span>Client</span><span>Protocol</span><span>IN</span><span>OUT</span><span>Total</span></div><div v-for="x in filteredTrafficRows" :key="x.client_id" class="traffic-usage-row"><span><b>{{x.client_name}}</b><small>{{x.client_id.slice(0,8)}}</small></span><span>{{x.protocol}}</span><span>{{formatBytes(x.bytes_in)}}</span><span>{{formatBytes(x.bytes_out)}}</span><strong>{{formatBytes(x.total_bytes)}}</strong></div><div v-if="!filteredTrafficRows.length" class="empty">داده‌ای برای این فیلتر وجود ندارد.</div></div></div>
<div class="panel"><div class="panel-head"><div><h2>وضعیت سهمیه</h2><small>کل · روزانه · ماهانه · انقضا</small></div><button v-if="me.role!=='tenant_operator'" class="primary" @click="modal='quota'">+ تنظیم</button></div><div class="quota-summary"><div><b>{{quotaNormalCount}}</b><small>Normal</small></div><div><b>{{quotaWarningCount}}</b><small>Warning</small></div><div><b>{{quotaLimitCount}}</b><small>Limit</small></div></div><div class="quota-list"><div v-for="q in quotaRows" :key="q.client_id" class="quota-row"><div class="quota-row-head"><b>{{q.client_name}}</b><span :class="'quota-state '+String(q.state).toLowerCase()">{{q.state}}</span></div><div class="quota-meters"><div v-if="q.total_bytes"><small>کل {{formatBytes(q.used_bytes)}} / {{formatBytes(q.total_bytes)}}</small><div class="meter"><i :style="{width:(q.total_pct||0)+'%'}"></i></div></div><div v-if="q.daily_bytes"><small>روزانه {{formatBytes(q.daily_used_bytes)}} / {{formatBytes(q.daily_bytes)}}</small><div class="meter"><i :style="{width:(q.daily_pct||0)+'%'}"></i></div></div><div v-if="q.monthly_bytes"><small>ماهانه {{formatBytes(q.monthly_used_bytes)}} / {{formatBytes(q.monthly_bytes)}}</small><div class="meter"><i :style="{width:(q.monthly_pct||0)+'%'}"></i></div></div></div></div><div v-if="!quotaRows.length" class="empty">هنوز سهمیه‌ای برای کلاینت‌ها تعریف نشده است.</div></div></div></div>
<div class="notice traffic-snapshot-note">برای محاسبه دقیق مصرف روزانه/ماهانه، روی «جمع‌آوری و بروزرسانی» بزن تا Snapshot جدید ثبت شود. این داده‌ها از شمارنده‌های ثبت‌شده Node تغذیه می‌شوند.</div>
</div></section>
<section v-else-if="section==='admins'"><div class="rbac-page">
<div class="rbac-head"><div><span class="eyebrow">ACCESS CONTROL</span><h1>مدیران و RBAC</h1><p>مدیریت مدیران، نقش‌ها، Permissionها و Scope اینباندها در سطح Tenant</p></div><button class="primary" @click="openAdminCreate">+ مدیر جدید</button></div>
<div class="stats rbac-stats"><article><small>کل مدیران</small><strong>{{adminRows.length}}</strong><em>Tenant admins</em></article><article><small>فعال</small><strong>{{adminRows.filter(x=>x.enabled).length}}</strong><em>Active</em></article><article><small>نمایندگان</small><strong>{{adminRows.filter(x=>x.role==='representative').length}}</strong><em>Scoped access</em></article><article><small>کلاینت نمایندگان</small><strong>{{adminRows.reduce((n,x)=>n+(x.own_clients||0),0)}}</strong><em>Owned clients</em></article></div>
<div class="panel rbac-toolbar rbac-filter-panel"><div class="rbac-search"><span>⌕</span><input v-model="adminSearch" placeholder="جستجو ایمیل، نقش یا وضعیت"><button v-if="adminSearch" class="filter-clear" @click="adminSearch=''">پاک کردن</button></div><div class="rbac-filter-actions"><select v-model="adminRoleFilter"><option value="">همه نقش‌ها</option><option value="tenant_operator">اپراتور</option><option value="representative">نماینده</option></select><select v-model="adminStatusFilter"><option value="">همه وضعیت‌ها</option><option value="active">فعال</option><option value="disabled">غیرفعال</option></select></div><div class="rbac-legend"><span><i class="role-dot manager"></i>مدیر</span><span><i class="role-dot representative"></i>نماینده</span><span><i class="role-dot operator"></i>اپراتور</span></div></div><div class="rbac-results-bar"><span>{{adminPageStart}}–{{adminPageEnd}} از {{filteredAdminRows.length}} مدیر</span><small>هر صفحه ۴ مدیر</small></div>
<div class="rbac-grid"><div class="admin-card" v-for="a in paginatedAdminRows" :key="a.id"><div class="admin-card-top"><div class="admin-avatar">{{a.email.slice(0,1).toUpperCase()}}</div><div><h3>{{a.email}}</h3><span class="role-chip" :class="a.role">{{adminRoleLabel(a.role)}}</span></div><span class="enabled-chip" :class="{off:!a.enabled}">{{a.enabled?'فعال':'غیرفعال'}}</span></div>
<div class="admin-meta"><span><small>کلاینت‌های خود</small><b>{{a.own_clients||0}}</b></span><span><small>Scope اینباند</small><b>{{a.role==='representative'?(a.inbound_ids?.length||0):'همه'}}</b></span></div><div class="admin-quota"><div class="quota-line"><span><small>مصرف ترافیک</small><b>{{formatBytes(a.traffic_used_bytes||0)}} <em v-if="a.traffic_limit_bytes">/ {{formatBytes(a.traffic_limit_bytes)}}</em><em v-else>نامحدود</em></b></span><span :class="'quota-state '+String(a.quota_state||'NORMAL').toLowerCase()">{{a.quota_state==='LIMIT_REACHED'?'حجم تمام':a.quota_state==='EXPIRED'?'منقضی':a.quota_state==='WARNING'?'نزدیک سقف':'عادی'}}</span></div><div v-if="a.traffic_limit_bytes" class="admin-meter"><i :style="{width:(a.traffic_usage_pct||0)+'%'}"></i></div><div class="quota-tags"><span>حجم: {{a.traffic_limit_bytes?((a.traffic_limit_bytes/1073741824).toFixed(2)+' GB'):'نامحدود'}}</span><span>مدت: {{a.quota_duration_days||0}} روز{{a.quota_duration_days?'':' · نامحدود'}}</span><span v-if="a.quota_expires_at">انقضا: {{new Date(a.quota_expires_at).toLocaleDateString('fa-IR')}}</span></div></div>
<div v-if="a.role==='representative'" class="scope-preview"><span v-for="id in (a.inbound_ids||[]).slice(0,3)" :key="id">{{(inboundRows.find(x=>x.id===id)||{}).name||id.slice(0,8)}}</span><em v-if="(a.inbound_ids||[]).length>3">+{{a.inbound_ids.length-3}}</em></div>
<div class="admin-actions"><button class="icon" @click="openAdminEdit(a)">ویرایش RBAC</button><button v-if="a.enabled" class="icon danger-btn" @click="disableAdmin(a)">غیرفعال</button><button class="icon danger-btn" @click="deleteAdmin(a)">حذف مدیر</button></div></div><div v-if="!filteredAdminRows.length" class="empty">مدیری مطابق فیلترها پیدا نشد.</div></div><div v-if="filteredAdminRows.length" class="rbac-pagination"><button class="icon" :disabled="adminPage<=1" @click="adminPage--">قبلی</button><div><b>صفحه {{adminPage}}</b><small>از {{adminPageCount}}</small></div><button class="icon" :disabled="adminPage>=adminPageCount" @click="adminPage++">بعدی</button></div>
<div class="panel permission-panel"><div class="panel-head"><div><h2>Permission Matrix</h2><small>مجوزها بر اساس نقش و اصل Least Privilege اعمال می‌شوند.</small></div></div><div class="permission-grid"><div><b>نماینده</b><span>فقط Client: مشاهده، ساخت، ویرایش و Revoke کلاینت‌های خودش + Inboundهای Scope شده</span></div><div><b>اپراتور</b><span>مشاهده Node / Inbound / Client / Traffic / Audit</span></div></div></div>
</div></section><section v-else-if="section==='audit'"><div class="audit-page">
<div class="audit-head"><div><small class="eyebrow">SECURITY & COMPLIANCE</small><h1>گزارش حسابرسی</h1><p>تمام فعالیت‌های حساس Control Plane، مدیران و عملیات زیرساخت را به‌صورت tenant-scoped بررسی کن.</p></div><div class="audit-head-actions"><select v-model.number="auditDays"><option :value="1">۲۴ ساعت</option><option :value="7">۷ روز</option><option :value="30">۳۰ روز</option><option :value="90">۹۰ روز</option></select><button class="primary" @click="load">↻ بروزرسانی</button></div></div>
<div class="audit-stats"><article><small>کل رویدادها</small><b>{{filteredAuditRows.length}}</b><span>در بازه انتخابی</span></article><article><small>موفق</small><b>{{auditSuccessCount}}</b><span class="audit-good">Operations OK</span></article><article><small>ناموفق</small><b>{{auditFailedCount}}</b><span class="audit-bad">Needs review</span></article><article><small>کاربران فعال در لاگ</small><b>{{auditActorCount}}</b><span>Actorهای یکتا</span></article></div>
<div class="panel audit-filter-panel"><div class="audit-filter-grid"><label><small>جستجو</small><input v-model="auditSearch" placeholder="Action، Resource، مدیر، IP یا Request ID"></label><label><small>Action</small><select v-model="auditActionFilter"><option value="">همه عملیات</option><option v-for="x in auditActions" :value="x">{{auditActionLabel(x)}}</option></select></label><label><small>نتیجه</small><select v-model="auditResultFilter"><option value="">همه نتایج</option><option value="success">موفق</option><option value="ok">موفق</option><option value="failed">ناموفق</option><option value="error">خطا</option></select></label><button class="icon" @click="auditSearch='';auditActionFilter='';auditResultFilter='';auditDays=30">پاک کردن فیلتر</button></div></div>
<div class="panel audit-log-panel"><div class="panel-head"><div><h2>Activity Timeline</h2><small>جدیدترین رویدادها ابتدا نمایش داده می‌شوند.</small></div><div class="audit-result-count">{{auditPageStart}}–{{auditPageEnd}} از {{filteredAuditRows.length}}</div></div>
<div v-if="paginatedAuditRows.length" class="audit-list"><article v-for="x in paginatedAuditRows" :key="x.id" class="audit-item"><div class="audit-icon" :class="auditResultLabel(x.result)==='موفق'?'good':'bad'">{{auditResultLabel(x.result)==='موفق'?'✓':'!'}}</div><div class="audit-main"><div class="audit-title"><b>{{auditActionLabel(x.action)}}</b><span class="audit-chip">{{x.resource}}</span><span v-if="x.resource_id" class="audit-chip muted">{{String(x.resource_id).slice(0,12)}}</span></div><div class="audit-meta"><span>👤 {{x.actor_email||'Unknown'}}</span><span v-if="x.ip">IP: {{x.ip}}</span><span>{{x.created_at?new Date(x.created_at).toLocaleString('fa-IR'):'—'}}</span></div><div v-if="x.details&&Object.keys(x.details).length" class="audit-details">{{JSON.stringify(x.details)}}</div></div><span class="audit-result" :class="auditResultLabel(x.result)==='موفق'?'good':'bad'">{{auditResultLabel(x.result)}}</span></article></div><div v-else class="empty audit-empty">در این بازه رویدادی مطابق فیلترها پیدا نشد.</div></div>
<div v-if="filteredAuditRows.length" class="rbac-pagination audit-pagination"><button class="icon" :disabled="auditPage<=1" @click="auditPage--">قبلی</button><div><b>صفحه {{auditPage}}</b><small>از {{auditPageCount}}</small></div><button class="icon" :disabled="auditPage>=auditPageCount" @click="auditPage++">بعدی</button></div>
</div></section>
<section v-else-if="section==='settings'" class="settings-page">
<div class="settings-hero"><div><small class="eyebrow">CONTROL PLANE CONFIGURATION</small><h1>تنظیمات</h1><p>تنظیمات اصلی Tenant، پیش‌فرض‌های ساخت Client و کنترل‌های امنیتی پنل را از یکجا مدیریت کن.</p></div><div class="settings-actions"><span class="save-state" v-if="settingsDraft?.updated_at">آخرین ذخیره: {{new Date(settingsDraft.updated_at).toLocaleString('fa-IR')}}</span><button class="icon" @click="resetSettings">بازنشانی</button><button class="primary" :disabled="loading" @click="saveSettings">{{loading?'در حال ذخیره…':'ذخیره تغییرات'}}</button></div></div>
<div v-if="settingsDraft" class="settings-grid">
<div class="settings-main">
<div class="settings-card"><div class="settings-card-head"><div><span class="settings-icon">◈</span><div><h2>عمومی و هویت پنل</h2><small>نام، زبان و منطقه زمانی Control Plane</small></div></div></div><div class="settings-form-grid"><label>نام پنل<input v-model="settingsDraft.panel_name" maxlength="160"></label><label>زبان پیش‌فرض<select v-model="settingsDraft.language"><option value="fa">فارسی</option><option value="en">English</option></select></label><label>منطقه زمانی<input v-model="settingsDraft.timezone" placeholder="Europe/Berlin"></label><label>DNS پیش‌فرض<input v-model="settingsDraft.default_dns" placeholder="1.1.1.1"></label></div></div>
<div class="settings-card"><div class="settings-card-head"><div><span class="settings-icon">◎</span><div><h2>پیش‌فرض ساخت Client</h2><small>مقادیر پیش‌فرض برای عملیات بعدی؛ ۰ یعنی بدون سقف</small></div></div></div><div class="settings-form-grid"><label>Protocol پیش‌فرض<select v-model="settingsDraft.default_protocol"><option value="wireguard">WireGuard</option><option value="amneziawg">AmneziaWG</option><option value="openvpn">OpenVPN</option></select></label><label>سهمیه پیش‌فرض (GB)<input v-model.number="settingsDraft.default_client_quota_gb" type="number" min="0"></label><label>مدت پیش‌فرض (روز)<input v-model.number="settingsDraft.default_client_duration_days" type="number" min="0"></label></div><div class="settings-note">این مقادیر به‌عنوان استاندارد Tenant ذخیره می‌شوند و برای توسعه فرم‌های ساخت Client قابل استفاده‌اند.</div></div>
<div class="settings-card"><div class="settings-card-head"><div><span class="settings-icon">⌁</span><div><h2>امنیت و نشست</h2><small>سیاست‌های پایه امنیتی و نگهداری لاگ</small></div></div></div><div class="settings-form-grid"><label>مدت نشست (دقیقه)<input v-model.number="settingsDraft.session_timeout_minutes" type="number" min="5"></label><label>نگهداری Audit Logs (روز)<input v-model.number="settingsDraft.audit_retention_days" type="number" min="1"></label></div><label class="settings-toggle"><input type="checkbox" v-model="settingsDraft.require_mfa"><span><b>الزام MFA</b><small>فعال‌سازی این گزینه سیاست را در تنظیمات Tenant ثبت می‌کند.</small></span><i :class="{on:settingsDraft.require_mfa}"></i></label></div>
</div>
<aside class="settings-side"><div class="settings-summary"><div class="settings-summary-logo">P</div><h3>{{settingsDraft.panel_name||'PRIMEVPN'}}</h3><small>Control Plane v1.0.0</small><div class="settings-status"><i></i> Tenant Configuration Active</div><dl><div><dt>Protocol</dt><dd>{{settingsDraft.default_protocol}}</dd></div><div><dt>DNS</dt><dd>{{settingsDraft.default_dns}}</dd></div><div><dt>Language</dt><dd>{{settingsDraft.language==='fa'?'فارسی':'English'}}</dd></div><div><dt>Quota</dt><dd>{{settingsDraft.default_client_quota_gb||0}} GB</dd></div></dl></div><div class="settings-checklist"><h3>Configuration Checklist</h3><div><i>✓</i><span>Tenant isolation</span></div><div><i>✓</i><span>RBAC & permissions</span></div><div><i>✓</i><span>Audit logging</span></div><div><i>✓</i><span>Secure API</span></div></div></aside>
</div><div v-else class="empty">تنظیمات در حال بارگذاری است…</div>
</section>
</main>
</div>
<div v-if="modal" class="modal-backdrop"><div class="modal">
<button class="close" @click="modal=null">×</button>
<div v-if="modal==='artifact'"><h2>Config Artifact</h2><p>{{artifact?.protocol}} · {{artifactName}}</p><textarea class="artifact" readonly :value="artifact?.payload"></textarea><div class="grid2"><button class="primary wide" @click="downloadArtifact">دانلود فایل</button><button class="icon wide" @click="copyArtifact">کپی Config</button></div></div><div v-if="modal==='mfa'"><h2>تأیید MFA</h2><input v-model="mfaCode" inputmode="numeric" placeholder="کد ۶ رقمی"><button class="primary wide" @click="verifyMfa">تأیید</button></div>
<div v-if="modal==='node'"><h2>{{t("افزودن VPS / Node","Add VPS / Node")}}</h2><p class="modal-help">{{t("روش جدید: روی VPS فقط یک دستور نصب اجرا کن؛ نیازی به وارد کردن رمز SSH نیست. توکن نصب یک‌بارمصرف است.","New method: run one installer command on the VPS. No SSH password is required. The install token is single-use.")}}</p><input v-model="nodeForm.name" placeholder="نام Node"><input v-model="nodeForm.address" placeholder="IP عمومی VPS"><button class="primary wide" @click="act(async()=>{const r=await nodes.installToken({name:nodeForm.name,address:nodeForm.address});installArtifact.value=r;return r},t('دستور نصب ساخته شد؛ آن را روی VPS اجرا کن','Install command generated; run it on the VPS'))">{{t("ساخت دستور نصب Node","Generate Node Install Command")}}</button><div v-if="installArtifact" class="install-box"><small>{{t("دستور را روی VPS با دسترسی root اجرا کن:","Run this command on the VPS as root:")}}</small><textarea class="artifact" readonly :value="installArtifact.install_command"></textarea><button class="icon wide" @click="copyInstallCommand">{{t("کپی دستور","Copy command")}}</button><small class="security-note">{{t("توکن داخل دستور قرار دارد و فقط یک‌بار و برای مدت محدود معتبر است. بعد از اجرای موفق، Node خودش در پنل به READY متصل می‌شود.","The token is embedded in the command and is single-use with a short expiry. After successful installation, the Node registers itself as READY.")}}</small></div></div><div v-if="modal==='node-install'"><h2>{{t("نصب Node روی VPS","Install Node on VPS")}}</h2><p class="modal-help">{{t("این دستور را داخل ترمینال همان VPS اجرا کن. توکن یک‌بارمصرف است و پس از نصب مصرف می‌شود.","Run this command in the terminal of that VPS. The bootstrap token is one-time and consumed during installation.")}}</p><textarea class="artifact" readonly :value="installCommand"></textarea><div class="grid2"><button class="primary wide" @click="copyInstallCommand">کپی دستور</button><button class="icon wide" @click="modal=null">بستن</button></div><small class="security-note">Node ID: {{installNodeInfo?.node_id}} · اعتبار توکن: ۱۵ دقیقه</small></div>
<div v-if="modal==='inbound'"><h2>{{inboundEditingId?'ویرایش Inbound':'Inbound جدید'}}</h2><p class="modal-help">پروتکل، Node و مشخصات شبکه را تنظیم کن. تغییر Protocol برای Inbound موجود مجاز نیست.</p><select v-model="inboundForm.node_id"><option value="">Node</option><option v-for="n in nodeRows" :value="n.id">{{n.name}}</option></select><select v-model="inboundForm.protocol" :disabled="!!inboundEditingId"><option value="wireguard">WireGuard</option><option value="amneziawg">AmneziaWG</option><option value="openvpn">OpenVPN</option></select><input v-model="inboundForm.name" placeholder="نام Inbound"><div class="grid2"><input v-model.number="inboundForm.listen_port" type="number" placeholder="Port"><input v-model="inboundForm.interface" placeholder="Interface"></div><div class="grid2"><input v-model="inboundForm.address" placeholder="Address/CIDR"><input v-model="inboundForm.network" placeholder="Network/CIDR"></div><input v-model="inboundForm.dns" placeholder="DNS"><button class="primary wide" :disabled="loading" @click="saveInbound">{{loading?'در حال ذخیره…':(inboundEditingId?'ذخیره تغییرات':'ساخت Inbound')}}</button></div>
<div v-if="modal==='inbound-detail'"><h2>{{clientDetail?.name}}</h2><div class="detail-grid"><div><small>Protocol</small><b>{{clientDetail?.protocol}}</b></div><div><small>State</small><b>{{clientDetail?.desired_state||clientDetail?.state}}</b></div><div><small>Node ID</small><b>{{clientDetail?.node_id}}</b></div><div><small>Port</small><b>{{clientDetail?.listen_port}}</b></div><div><small>Interface</small><b>{{clientDetail?.interface}}</b></div><div><small>Address</small><b>{{clientDetail?.address}}</b></div><div><small>Network</small><b>{{clientDetail?.network}}</b></div><div><small>DNS</small><b>{{clientDetail?.dns||'—'}}</b></div></div><div class="inbound-modal-summary"><span><b>{{inboundClientsCount(clientDetail?.id)}}</b><small>کلاینت</small></span><span><b>{{inboundOnlineCount(clientDetail?.id)}}</b><small>آنلاین</small></span><span><b>{{clientDetail?.enabled===false?'خاموش':'فعال'}}</b><small>Runtime</small></span></div><div class="grid2"><button class="primary wide" @click="modal=null;act(()=>inbounds.sync(clientDetail.id),'Inbound synced')">Sync / Apply</button><button v-if="me.role!=='tenant_operator'" class="icon wide" @click="modal=null;openInboundEdit(clientDetail)">ویرایش</button></div></div>
<div v-if="modal==='node-detail'"><h2>{{clientDetail?.name}}</h2><div class="detail-grid"><div><small>Address</small><b>{{clientDetail?.address}}</b></div><div><small>State</small><b>{{clientDetail?.state}}</b></div><div><small>Agent URL</small><b>{{clientDetail?.agent_url||'—'}}</b></div><div><small>Node ID</small><b>{{clientDetail?.id}}</b></div><div><small>آخرین Heartbeat</small><b>{{clientDetail?.last_seen_at?new Date(clientDetail.last_seen_at).toLocaleString('fa-IR'):'—'}}</b></div><div><small>Capabilities</small><b>{{clientDetail?.capabilities?Object.keys(clientDetail.capabilities).join(' · '):'—'}}</b></div></div><div class="node-health node-modal-health"><span><i :class="{ok:clientDetail?.state==='READY'||clientDetail?.state==='DEGRADED'}"></i>Control Plane</span><span><i :class="{ok:!!clientDetail?.agent_url}"></i>Agent</span><span><i :class="{ok:!!clientDetail?.last_seen_at}"></i>Heartbeat</span></div><div class="grid2"><button v-if="me.role!=='tenant_operator'" class="primary wide" @click="modal=null;provision(clientDetail.id)">Provision / Sync دوباره</button><button v-if="me.role!=='tenant_operator'" class="icon danger-btn wide" @click="modal=null;deleteNode(clientDetail)">حذف نود</button></div></div>
<div v-if="modal==='client'"><h2>Client جدید</h2><p class="modal-help">کلاینت ساخته می‌شود، Credential امن تولید می‌شود و فایل WireGuard/AmneziaWG یا OpenVPN برای دانلود آماده می‌شود.</p><select v-model="clientForm.inbound_id"><option value="">Inbound مورد نظر</option><option v-for="i in allowedClientInbounds" :value="i.id">{{i.name}} / {{i.protocol}}</option></select><input v-model="clientForm.name" placeholder="نام کلاینت"><input v-model="clientForm.assigned_address" placeholder="10.10.0.2/32"><div class="grid2"><input v-model="clientForm.expires_at" type="datetime-local" placeholder="زمان انقضا"><input v-model.number="clientForm.warning_ratio" type="number" min="1" max="100" placeholder="هشدار سهمیه %"></div><div class="grid3"><input v-model="clientForm.total_gb" inputmode="decimal" placeholder="حجم کل (GB)"><input v-model="clientForm.daily_gb" inputmode="decimal" placeholder="سقف روزانه (GB)"><input v-model="clientForm.monthly_gb" inputmode="decimal" placeholder="سقف ماهانه (GB)"></div><input v-model="clientForm.max_devices" type="number" min="1" placeholder="حداکثر دستگاه"><button class="primary wide" :disabled="loading" @click="createClient">{{loading?'در حال ساخت…':'ساخت + تولید فایل کانفیگ'}}</button></div>
<div v-if="modal==='client-edit'"><h2>ویرایش Client</h2><input v-model="clientForm.name" placeholder="نام کلاینت"><input v-model="clientForm.expires_at" type="datetime-local"><div class="grid3"><input v-model="clientForm.total_gb" placeholder="حجم کل (GB)"><input v-model="clientForm.daily_gb" placeholder="سقف روزانه (GB)"><input v-model="clientForm.monthly_gb" placeholder="سقف ماهانه (GB)"></div><input v-model="clientForm.max_devices" type="number" min="1" placeholder="حداکثر دستگاه"><input v-model.number="clientForm.warning_ratio" type="number" min="1" max="100" placeholder="هشدار سهمیه %"><button class="primary wide" @click="saveClientEdit">ذخیره تغییرات</button></div>
<div v-if="modal==='client-detail'"><h2>{{clientDetail?.name}}</h2><div class="detail-grid"><div><small>Inbound</small><b>{{clientDetail?.inbound_name}}</b></div><div><small>Protocol</small><b>{{clientDetail?.protocol}}</b></div><div><small>IP</small><b>{{clientDetail?.assigned_address}}</b></div><div><small>Node</small><b>{{clientDetail?.node_name}}</b></div><div><small>IN</small><b>{{formatBytes(clientDetail?.traffic_in||0)}}</b></div><div><small>OUT</small><b>{{formatBytes(clientDetail?.traffic_out||0)}}</b></div><div><small>تاریخ ساخت</small><b>{{new Date(clientDetail?.created_at).toLocaleString('fa-IR')}}</b></div><div><small>انقضا</small><b>{{clientDetail?.expires_at?new Date(clientDetail.expires_at).toLocaleString('fa-IR'):'بدون انقضا'}}</b></div></div><div class="quota-detail"><b>سهمیه</b><span>{{clientDetail?.quota_total?formatBytes(clientDetail.quota_used)+' / '+formatBytes(clientDetail.quota_total):'بدون سقف'}} · روزانه {{clientDetail?.quota_daily?formatBytes(clientDetail.quota_daily):'—'}} · ماهانه {{clientDetail?.quota_monthly?formatBytes(clientDetail.quota_monthly):'—'}} · دستگاه {{clientDetail?.max_devices||'∞'}}</span><i>{{clientDetail?.quota_state||'NORMAL'}}</i></div><h3>دستگاه‌ها ({{clientDevices.length}})</h3><div class="device-list"><div v-for="d in clientDevices" :key="d.id"><b>{{d.assigned_address||'—'}}</b><small>{{d.fingerprint}}</small><time>{{d.last_seen_at?new Date(d.last_seen_at).toLocaleString('fa-IR'):'هنوز متصل نشده'}}</time></div><div v-if="!clientDevices.length" class="empty">هنوز دستگاهی ثبت نشده است.</div></div><div class="grid2"><button class="primary wide" @click="issueConfig(clientDetail.id)">تولید / دانلود Config</button><button v-if="clientDetail?.status!=='REVOKED'" class="icon wide danger-btn" @click="modal=null;revokeClient(clientDetail.id)">Revoke</button></div></div>
<div v-if="modal==='admin'"><h2>{{adminEditingId?'ویرایش مدیر و RBAC':'مدیر جدید'}}</h2><p class="modal-help">نقش و سطح دسترسی را مشخص کن. نماینده فقط به Scopeهای انتخاب‌شده و کلاینت‌هایی که خودش ساخته دسترسی دارد.</p>
<input v-if="!adminEditingId" v-model="adminForm.email" placeholder="Email"><input v-if="!adminEditingId" v-model="adminForm.password" type="password" placeholder="Password ≥ 12 chars">
<select v-model="adminForm.role"><option value="tenant_operator">اپراتور</option><option value="representative">نماینده</option></select>
<div class="admin-quota-form"><div class="quota-form-head"><b>سهمیه مدیر</b><small>۰ یعنی نامحدود؛ حجم و مدت مستقل از هم هستند.</small></div><div class="grid2"><label>حجم کل استفاده (GB)<input v-model="adminForm.quota_gb" type="number" min="0" step="0.1" placeholder="0 = نامحدود"></label><label>مدت استفاده (روز)<input v-model="adminForm.duration_days" type="number" min="0" step="1" placeholder="0 = نامحدود"></label></div><div class="quota-examples"><span>۰ GB + ۰ روز = نامحدود</span><span>۰ GB + ۳۰ روز = ۳۰ روز نامحدود</span><span>۵۰ GB + ۶۰ روز = ۵۰ GB / ۶۰ روز</span></div></div>
<div v-if="adminForm.role==='representative'" class="rbac-scope-box"><div class="scope-title"><b>Inbound Scope</b><small>نماینده فقط می‌تواند روی این Inboundها Client بسازد و کلاینت‌های خودش را مدیریت کند.</small></div><label class="check-row" v-for="i in adminInboundRows" :key="i.id"><input type="checkbox" :value="i.id" v-model="adminForm.inbound_ids"><span><b>{{i.name}}</b><small>{{i.protocol}} · Port {{i.listen_port}}</small></span></label><div v-if="!adminInboundRows.length" class="empty">Inbound برای انتخاب وجود ندارد.</div></div>
<label class="check-row admin-enabled"><input type="checkbox" v-model="adminForm.enabled"><span><b>حساب فعال باشد</b><small>حساب غیرفعال دیگر اجازه ورود ندارد.</small></span></label>
<button class="primary wide" :disabled="loading" @click="saveAdmin">{{loading?'در حال ذخیره…':(adminEditingId?'ذخیره تغییرات':'ساخت مدیر')}}</button></div><div v-if="modal==='quota'"><h2>Quota</h2><select v-model="quotaForm.client_id"><option value="">Client</option><option v-for="c in clientRows" :value="c.id">{{c.name}}</option></select><input v-model="quotaForm.total_bytes" type="number" placeholder="Total bytes"><input v-model="quotaForm.daily_bytes" type="number" placeholder="Daily bytes"><input v-model="quotaForm.monthly_bytes" type="number" placeholder="Monthly bytes"><input v-model="quotaForm.max_devices" type="number" placeholder="Max devices"><input v-model.number="quotaForm.warning_ratio" type="number" placeholder="Warning %"><button class="primary wide" @click="act(()=>quotas.set({...quotaForm,total_bytes:quotaForm.total_bytes?Number(quotaForm.total_bytes):null,daily_bytes:quotaForm.daily_bytes?Number(quotaForm.daily_bytes):null,monthly_bytes:quotaForm.monthly_bytes?Number(quotaForm.monthly_bytes):null,max_devices:quotaForm.max_devices?Number(quotaForm.max_devices):null}),'Quota ذخیره شد')">ذخیره</button></div>
</div></div>
</template>